GET http://localhost:3001/todos/?status=TO%20DO

###
GET http://localhost:3001/todos/?priority=HIGH

###
GET http://localhost:3001/todos/?priority=HIGH&status=IN%20PROGRESS

###
GET http://localhost:3001/todos/?search_q=event
###

GET http://localhost:3001/todos/2/

###

POST http://localhost:3001/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
###
PUT http://localhost:3001/todos/3/
Content-Type: application/json

{
    "status": "TO DO"
}
###
PUT http://localhost:3001/todos/2/
Content-Type: application/json

{
    "priority": "HIGHS"
}

###
PUT http://localhost:3001/todos/2/
Content-Type: application/json

{
    "todo": "Some task"
}


###
DELETE http://localhost:3001/todos/10/